image: rays3t/sourcemod-plugins-builder-ci
build:
    stage: build
    script: 
    - spcomp
    - mkdir -p package/cstrike/addons/sourcemod/scripting/include
    - mkdir -p package/cstrike/addons/sourcemod/translations
    - mkdir -p package/cstrike/addons/sourcemod/plugins
    - mkdir -p package/cstrike/cfg
    - cp -r compiled/* package/cstrike/addons/sourcemod/plugins
    - cp -r cfg/* package/cstrike/cfg
    - cp -r translations/* package/cstrike/addons/sourcemod/translations
    
    artifacts:
        name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}"
        paths:
        - package/*
